name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run script
        uses: actions/python-script@v2
        with:
          script: https://raw.githubusercontent.com/jairtamara/tallerpython/main/tallerpython.py
