name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout script
        uses: actions/checkout@v2
        with:
          repository: jairtamara/tallerpython
          path: main/repositorios/tallerpython.py      
      - name: Run script
        run: |
          python tallerpython.py
