name: Winwdos

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     
      - name: Run Python script
        id: python_step
        run: |
         Invoke-WebRequest -Uri https://raw.githubusercontent.com/jairtamara/tallerpython/jairtamara-patch-1/tallerpython.py | python - 
