name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: 'win'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     
      - name: Run Python script
        run: |
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/jairtamara/tallerpython/main/tallerpython.py -OutFile tallerpython.py C:\Users\jair-\AppData\Local\Programs\Python\Python312\python.exe tallerpython.py
