name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: 'win'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     
      - name: Run Python script
        run: |
          curl -s https://raw.githubusercontent.com/jairtamara/tallerpython/main/tallerpython.py | python -
