name: linux......

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pip install gitpython
      - name: Run Python script
        id: python_step
        run: |
          curl -s https://raw.githubusercontent.com/jairtamara/tallerpython/jairtamara-patch-1/tallerpython.py | python - 

      - name: Upload log.diff to GitHub summary
        uses: actions/upload-artifact@v3
        with:
          name: log.diff
          path: ./log.diff   

