name: linux

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pip install gitpython
      - name: Run Python script
        id: python_step
        run: |
          curl -s https://raw.githubusercontent.com/jairtamara/tallerpython/main/tallerpython1.py | python           
      - name: Mostrar diferencias
        run: echo "${{ steps.python_step.outputs.stdout }}"   
