# prueba cambios entre repo en runner y repo antrior----

name: Validación de cambios y despliegue

on:
  push:
    branches: [main]
      

jobs:
  Valida-cambios-contra-repositorio-Anterior:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codigo    
      uses: actions/checkout@v3      
    - name: Validar cambios
      id: check_changes    

      run: |
        echo "Base ref: ${{ github.base_ref }}"
        echo "Head ref: ${{ github.head_ref }}"
        MODIFIED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})
        echo "Modified Files:"
        echo "$MODIFIED_FILES"

        
