# prueba cambios entre repo en runner y repo antrior----asdfasdf
a
name: Validación de cambios y despliegue

on:
  push:
    branches: [test]
      

jobs:
  Valida-cambios-contra-repositorio-Anterior:
    runs-on: 'win'

    steps:
    - name: Checkout codigo    
      uses: actions/checkout@v3 
      with:
        fetch-depth: 0
    - name: Validar cambios
      id: check_changes 
      

      run: |
        MODIFIED=$(git diff --name-only HEAD~ HEAD)
        echo "$MODIFIED"

        
