# prueba cambios entre repo en runner y repo antrior----

name: Validación de cambios y despliegue

on:
  push:
    branches: [feature/jtamara_pr]
      

jobs:
  Valida-cambios-contra-repositorio-Anterior:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codigo
      uses: actions/checkout@v3  

    - name: Validar cambios
      id: check_changes
      

              

      run: |  
          cambios=$(git diff --name-only ${{github.event.before}} ${{ github.sha }})
            if [ -n "$cambios" ]; then
              echo "Se han detectado cambios en el repositorio."
              echo "Cambios detectados: $cambios"
              echo "::set-output name=changes::true"
            else
              echo "No se han detectado cambios en el repositorio."
              echo "::set-output name=changes::false"

            fi       

 

   # - name: Desplegar si hay cambios
    #  if: steps.check_changes.outputs.changes == 'true'
     # run: |
        
